### ISSUE TITLE
Oops!  We encountered an error.  Please try again.

### ISSUE THREAD

**Issue by andyweedman** [tonesto7/nest-manager#456]
## Verify the following before opening an issue:

- [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
- [x] The SmartApp and Device are using the latest version.
- [x] You have reviewed the Readme for potential fixes.
- [x] That the Device Types have been _Published for You_.

## About Your Setup:
* How many Thermostats?: 1
* How many Protects? 2
* Are you Using the Nest Presence Device? No
* iOS or Android?: iOS
* Mobile App Version: 2.3.6

## Expected Behavior
Install smartapp, device handlers, enable oauth, add smartapp via iOS app, provide nest credentials to authorize w/ nest and continue install process.

## Current Behavior
Getting error during works with nest authorization Oops!  We encountered an error.  Please try again.

## Steps to Reproduce (for bugs)

Installed latest smartapps & device handlers from repo and published.  Enabled oauth for NST Manager.  Used SmartThings iOS app to add NST Manager.  During configuration of app I provided my nest credentials (yes they are the main credentials not a child/family account).  Accepted ack from Nest regarding what I was giving access to.  Error displayed on nest page Oops!  We encountered an error.  Please try again.

## Context
I was running Nest Manager (sorry I don't remember what version but I think it was 4.x).  I tried to update to the latest and it wasn't working.  I tried removing all devices, device handlers, smart apps and then performed a clean install.  
Please include a copy of your log under the IDE if possible>>>

1bea1728-27c6-469a-b31e-2e9a0afd2985  6:25:25 PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page
1bea1728-27c6-469a-b31e-2e9a0afd2985  6:24:52 PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page
1bea1728-27c6-469a-b31e-2e9a0afd2985  6:24:50 PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page
1bea1728-27c6-469a-b31e-2e9a0afd2985  6:24:50 PM: info ||| Nest Manager | appData.json File HAS Changed

**Comment by jp-stewart** [comment]
Hello, same results here as well. All the installation instructions work, but when logging into nest there is an error.

de7204c1-ca3e-4d3e-beed-fbd2caae1bfb  3:26:01 PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page
de7204c1-ca3e-4d3e-beed-fbd2caae1bfb  3:24:48 PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page
de7204c1-ca3e-4d3e-beed-fbd2caae1bfb  3:24:40 PM: info ||| Nest Manager | AuthToken not found: Directing to Login Page
de7204c1-ca3e-4d3e-beed-fbd2caae1bfb  3:24:39 PM: info ||| Nest Manager | appData.json File HAS Changed
![img_2327](https://cloud.githubusercontent.com/assets/12010417/26765891/8ddcae8e-493a-11e7-8cd5-2aec9393972d.PNG)

**Comment by holden777** [comment]
I have this same problem. I too could never t upgrade so I deleted everything and started from scratch. I get to this same point

**Comment by stubn** [comment]
I have the same problem. Fresh install from Code for me, first time setting up SmartThings for me. Has anyone managed to find a fix?

**Comment by holden777** [comment]
I did.  In the use only turn on oauth for nest manager not the other one also. As soon as I turned off oauth it worked. I had enabled it on both.

**Comment by tonesto7** [comment]
Sorry guys we are running out of available tokens.  So we are switching them around to the ones that have opening.   Give it a try once again.

**Comment by Tokn59** [comment]
Just tried 2 times after your message ... Still the same issue ... Thanks for trying to resolve so fast !!!!

**Comment by tonesto7** [comment]
ok try again

**Comment by stubn** [comment]
![img_1545](https://cloud.githubusercontent.com/assets/28849539/26831010/c1086f1c-4ac2-11e7-8995-d26c87fe1984.PNG)

I get this error screen now when I try and click 'accept'. Have tried it 6 times, force quit all apps.

**Comment by Tokn59** [comment]
Ok, tried, killed the app, restarted app, tried again but still the same "Oops" ...

**Comment by tonesto7** [comment]
wow.  i'm not awake yet.   Only part of the id and secret changed in our database.  Give it a try again.  Make sure to back out and re-install the app again

**Comment by Tokn59** [comment]
Re-install the Smartthings App on IOS you mean ? Or something else ?

**Comment by tonesto7** [comment]
The nest manager app

**Comment by Tokn59** [comment]
This SmartApp can't be deleted at this time because it is installed by one or more users

**Comment by jp-stewart** [comment]
Thanks ,trying again worked for me.

**Comment by Tokn59** [comment]
Ok .. deleted both SmartApps
Re-installed based on code
DID NOT do a repo update
Auth SmartApp Manager

Restarted Smartthings App on IOS
Start NST Manager SmartApp
Entered NEST credentials

**-> Your SmartThings Account is now connected to NEST !** 

Clicked "Next"

Set Location

Found Nest Protect devices correctly
Found Nest CAM device correctly

Get data from Nest devices correctly ! **Wow !!!!**
**Nest camera streaming :"There was a problem retrieving the livestream"**

# **THANK YOU SO MUCH !!!!!!!!**

**Comment by Tokn59** [comment]
Only camera streaming seems not to be working ? Rest looks just great !

When I enter the Camera : **Camera ID Not Found**

**PublicShareEnable : Enabled
![nest cam](https://cloud.githubusercontent.com/assets/9215231/26832633/5dce0444-4ad0-11e7-9f73-37ce8354c2cc.JPG)
**

**Comment by andyweedman** [comment]
Just now getting back to this issue.  I tried the day after I filed this issue and it worked.  Ditto on the camera streaming issue.  I'm seeing that too but all else is well.

**Comment by imnotbob** [comment]
If you are having issues still, we need to see IDE logs.

My suggestion:
 - recheck install instructions have been followed: http://thingsthataresmart.wiki/index.php?title=NST_Manager

- use the SmartThings forum send a private message to Tony and I with IDE logs of the issue.

In general we are not seeing issues in camera operations, so we suspect there is an install issue, or a ST platform issue affecting you.   We are happy to look to help you resolve.

**Comment by Tokn59** [comment]
Thank you ! I'll be on a holiday as of tomorrow  but right after that I will do the installation all opver again and let you know how that goes. Kind Regards and thanks for your support !

Tony

**Comment by jploo** [comment]
I am getting this problem, or "Can't reach nest.com right now. Try again soon." during the Works with Nest authorization on a fresh install. Is is possible there is a token problem again?

**Comment by pkboiler** [comment]
I tried a new install and have this issue as well.  Retried the install several times.  Tried manually.  No luck.  I have several other systems that "Work with Nest" and they all work (Google and Alexa).  Looks like everything (GIT, IDE, Apps, Handers) all installed and published correctly.  Oauth only Nest Manager App.  Is this the same token issue?

**Comment by imnotbob** [comment]
We have just updated the tokens, let us know if it is working now.

**Comment by xomikronx** [comment]
Please help.  I am still getting "Oops" error when accepting.

I've followed instructions from here: http://thingsthataresmart.wiki/index.php?title=NST_Manager#Installation_Instructions

**Comment by gbridge0** [comment]
I had same issue. Restarting SMARTThings iOS app fixed. Thanks!

**Comment by xomikronx** [comment]
I've even restarted my phone. Could it be related to the token again?

**Comment by ndorman21** [comment]
I am having the same issue since yesterday

**Comment by xomikronx** [comment]
How can we fix this long term?  Feels like a cat and mouse game with tokens running out.

**Comment by cphconsulting** [comment]
same issue for me today

**Comment by imnotbob** [comment]
should be working now

**Comment by Tokn59** [comment]
Hello, I just did a full repo update but I still have problems with the NEST Camera streaming. (See screeenshot attached) Should I do a full re-installation ? Thanks for your kiond help !!! Tony
![file](https://user-images.githubusercontent.com/9215231/27259034-01e8f9de-540a-11e7-850d-ef3821df6070.png)

**Comment by Juberstine** [comment]
Same Issue. Known problem? Had to reinstall the app and now I can't login.

**Comment by imnotbob** [comment]
Juberstine - have you been able to get in?

On the camera, likely should start a separate issue for that.  We would want to see IDE "Live Logging"

Please be sure you have updated the software to the latest

**Comment by slilie** [comment]
Getting the Oops error.  Are there issues with tokens again?

**Comment by imnotbob** [comment]
give it a try again, let us know if it works

**Comment by slilie** [comment]
Works now, thank you!

**Comment by jackandjim** [comment]
Also getting the oops error can you assist with resetting tokens again?

**Comment by jamess5** [comment]
I'm receiving the same "Oops! We encountered an error. Please try again." message too. Please could you help? @tonesto7

**Comment by billykwong** [comment]
I'm having the same issue.  Are there issues with tokens once again?

**Comment by amercer86** [comment]
I'm also having this issue.

**Comment by imnotbob** [comment]
Please see the instructions:

http://thingsthataresmart.wiki/index.php?title=NST_Manager

specifically:

http://thingsthataresmart.wiki/index.php?title=NST_Manager#Installation_Instructions
note the section on Nest Developer Account

https://community.smartthings.com/t/release-nst-manager-v5-0/83228/733

The issue is Nest will not give us more tokens (you can get them yourself), because they view the tokens as not kept private enough. Smarthings will not assist us in keeping them private enough to meet Nest’s ask. So we are stuck between rock and hard place.

**Comment by amercer86** [comment]
Ah, sorry. Breezed over this bit. Thank you!

**Comment by simonfea** [comment]
I'm also having this issue - any suggestions?  I cannot authorise my location from the Smart App...

**Comment by portauto** [comment]
imnotbob, thank you, following those instructions fixed the issue!

**Comment by amdsweb** [comment]
Hi getting the oops error as well. I've tried creating my own token but to be honest, I'm clueless even with your instructions above. Help!

**Comment by polarlamb** [comment]
I got the oops error. I had not deleted the empty space when I was copying to enter the product ID and product secret in the client id space. Once I deleted the empty space it resolved.

**Comment by bschimmel2** [comment]
Ive tried over and over installing multiple different ways.  Created my own key and I still cannot get it to let me log in.  I put in the nest username and password and it almost looks like I can and when I click accept at the bottom, it gives me the oops error at the top.  Please Help!

**Comment by Gregory2732** [comment]
Hello, having same issue as people above.  I have followed the instructions closely and tried all i can think of.  I made my own nest dev act, and got my own key's.  ive checked over and over to make sure the OAuth url is in correctly (https://graph.api.smartthings.com/oauth/callback), is this not correct?  or is there anything else to try?  **(Resolved!,  when copying the keys it automatically puts a space at the end of it, i deleted it on both and worked perfect!.  thank you)**

**Comment by martbazinet** [comment]
I'm receiving the same "Oops! We encountered an error. Please try again." message too. Please could you help? 
I'm reading that we may need to create a key but I don't know where to find this information...Can someone assist?

**Comment by b-radfrommalibu** [comment]
@tonesto7 Hi I'm new to github and smartthings. I'm trying to catch up and get nest manager (NST Manager) installed and working. I followed the instructions past the "Oops! We encountered an error. Please try again." all the way to  "Creating Your ID and Token for Nest". Unfortunately Nest is retiring Works with Nest connections effective August 31, 2019. Does this mean we cannot use nest manager anymore? Im not sure how to proceed with setup. 

Link: 
https://developers.nest.com/
